apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageviewerapi
spec:
  replicas: {{ .Values.ImageViewerAPIReplicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: imageviewerapi
  template:
    metadata:
      labels:
        app: imageviewerapi
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
      containers:
      - name: imageviewerapi
        image: {{ .Values.ImageRegistry }}/rdm/webservice/imageviewerapi:{{ .Chart.Version }}
        env:
        - name: COMPlus_gcServer
          value: "{{ .Values.COMPlus.gcServer }}"
        - name: COMPlus_gcConcurrent
          value: "{{ .Values.COMPlus.gcConcurrent }}"
        - name: ASPNETCORE_URLS
          value: "http://*:{{ .Values.ImageViewerAPIServicePort }}"
        volumeMounts:
        - mountPath: /var/run/secrets/vault-token
          name: vault-token
        ports:
        - containerPort: {{ .Values.ImageViewerAPIServicePort }}
      volumes:
      - name: vault-token
        projected:
          sources:
          - serviceAccountToken:
              path: vault-token
              expirationSeconds: 7200
              audience: vault
