apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: imageviewerapi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: minion
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ItmsApiIngressUrl }}
    http:
      paths:
      - path: /imageviewer(/|$)(.*)
        backend:
          serviceName: imageviewerapi
          servicePort: {{ .Values.ImageViewerAPIServicePort }}