apiVersion: v1
kind: Service
metadata:
  name: imageviewerapi
spec:
  selector:
    app: imageviewerapi
  ports:
    - protocol: TCP
      port: {{ .Values.ImageViewerAPIServicePort }}
      targetPort: {{ .Values.ImageViewerAPIServicePort }}