source "https://rubygems.org"

#gem "thor"
#gem "httparty"
gem "chef", "~> 14.13"
gem "foodcritic"
gem "rubocop"
gem "rubocop-performance"
gem "test-kitchen"
gem "kitchen-vagrant"
gem 'berkshelf'
gem 'ffi-yajl'
